package com.panwar2001.myapplication.ui

const val indieDataUrl1 ="https://panwar2001.github.io/indie-app-photos/indie-data-1.txt"

val index_1: List<Pair<String, String>> = listOf(
    Pair("COM", "comp.jpg"),
    Pair("R&D", "rd.jpg"),
    Pair("GLY-M", "glym.jpg"),
    Pair("GLY-MF", "glymf.jpg"),
    Pair("VG", "vg.jpg"),
    Pair("BRD", "brd.jpeg"),
    Pair("OLM", "olmi.jpeg"),
    Pair("OLM H", "olmh.jpeg"),
    Pair("OLM AM", "oam.jpeg"),
    Pair("TRIO", "trio.jpeg"),
    Pair("TEL", "tel.jpeg"),
    Pair("TEL H", "telh.jpeg"),
    Pair("T-AM", "tam.jpeg"),
    Pair("T-HA", "tha.jpeg"),
    Pair("CH", "ch.jpeg"),
    Pair("M50", "m50.jpeg"),
    Pair("CAP", "cap.jpeg"),
    Pair("CEFA", "cefa.jpg"),
    Pair("SG", "sg.jpg"),
    Pair("K2", "k2.jpg"),
    Pair("OZO", "ozo.jpg"),
    Pair("OZ-L", "ozl.jpg"),
    Pair("SP", "sp.jpg"),
    Pair("CLO-TH", "cloth.jpg"),
    Pair("JO-M", "jom.jpg"),
    Pair("LC", "lc.jpg"),
    Pair("REKI", "reki.jpg"),
    Pair("CORT", "cort.jpg")
)
val index_2 = listOf(
    Pair("COM", "comp.jpg"),
    Pair("R&D", "rd.jpg"),
    Pair("GLY-M", "glym.jpg"),
    Pair("GLY-MF", "glymf.jpg"),
    Pair("VG", "vg.jpg"),
    Pair("BRD", "brd.jpeg"),
    Pair("OLMI", "olmi.jpeg"),
    Pair("OLMI H", "olmh.jpeg"),
    Pair("OLMI AM", "oam.jpeg"),
    Pair("TRIO", "trio.jpeg"),
    Pair("TEL", "tel.jpeg"),
    Pair("TEL H", "telh.jpeg"),
    Pair("T-AM", "tam.jpeg"),
    Pair("T-HA", "tha.jpeg"),
    Pair("CH", "ch.jpeg"),
    Pair("M50", "m50.jpeg"),
    Pair("CAP", "cap.jpeg"),
    Pair("CEFO", "cefo.jpeg"),
    Pair("CV", "cv.jpeg"),
    Pair("CEFA", "cefa.jpg"),
    Pair("SG", "sg.jpg"),
    Pair("K2", "k2.jpg"),
    Pair("OZO", "ozo.jpg"),
    Pair("OZ-L", "ozl.jpg"),
    Pair("CLO", "clo.jpg"),
    Pair("SP", "sp.jpg"),
    Pair("CLO-TH", "cloth.jpg"),
    Pair("SPAA", "spaa.jpg"),
    Pair("TORI", "tori.jpeg"),
    Pair("TO-T", "tot.jpeg"),
    Pair("SIN", "sin.jpeg"),
    Pair("LIZO", "liso.jpeg"),
    Pair("JO-M", "jom.jpg"),
    Pair("LC", "lc.jpg"),
    Pair("REKI", "reki.jpg"),
    Pair("CORT", "cort.jpg"),
    Pair("LUNG", "lung.jpeg"),
    Pair("GUT", "gut.jpeg"),
    Pair("UDC", "udc.jpeg"),
    Pair("TIW", "tiw.jpeg"),
    Pair("RE- AC", "reac.jpg"),
    Pair("PRO", "prod.jpg")
)
